namespace: default
appName: approval-worker
version: 0.0.1
development: true

# 流程定义配置
workflow:
  # 流程部署共享文件夹,可选择用文件存储
  resourceDir: ../web/tmp

# 工作流引擎配置
temporal:
  type: BPMNWorkflowDef
  taskQueue: approval
  clientOptions:
    hostPort: localhost:7233
  workerOptions:
store:
  portal:
    driverName: mysql
    dsn: "root:@tcp(localhost:3306)/portal?parseTime=true&loc=Local"
  workflow:
    driverName: mysql
    dsn: "root:@tcp(localhost:3306)/workflow?parseTime=true&loc=Local"

httpWorker:
  # knockout auth url
  knockoutAuthUrl: http://localhost:8081/auth