// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeployDiagramInput struct {
	// 部署名称
	Name string `json:"name"`
	// 所属应用
	AppID int `json:"appID"`
	// 流程文件
	ResourceKey []string `json:"resourceKey,omitempty"`
	// 流程图文件ID
	ResourceID []int `json:"resourceID,omitempty"`
}

type StartProcessInput struct {
	// 流程定义ID
	ProcDefKey string `json:"procDefKey"`
	// 业务ID
	BusinessKey string `json:"businessKey"`
	// 流程变量
	Variables []*VariableInput `json:"variables,omitempty"`
}

type VariableInput struct {
	// 变量名称
	Name string `json:"name"`
	// 变量类型
	Type string `json:"type"`
	// 变量值
	Value string `json:"value"`
}
