// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/woocoos/workflow/ent/orgrole"
	"github.com/woocoos/workflow/ent/orgroleuser"
	"github.com/woocoos/workflow/ent/orguser"
	"github.com/woocoos/workflow/ent/predicate"

	"github.com/woocoos/workflow/ent/internal"
)

// OrgRoleUserQuery is the builder for querying OrgRoleUser entities.
type OrgRoleUserQuery struct {
	config
	ctx         *QueryContext
	order       []orgroleuser.OrderOption
	inters      []Interceptor
	predicates  []predicate.OrgRoleUser
	withOrgRole *OrgRoleQuery
	withOrgUser *OrgUserQuery
	modifiers   []func(*sql.Selector)
	loadTotal   []func(context.Context, []*OrgRoleUser) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OrgRoleUserQuery builder.
func (oruq *OrgRoleUserQuery) Where(ps ...predicate.OrgRoleUser) *OrgRoleUserQuery {
	oruq.predicates = append(oruq.predicates, ps...)
	return oruq
}

// Limit the number of records to be returned by this query.
func (oruq *OrgRoleUserQuery) Limit(limit int) *OrgRoleUserQuery {
	oruq.ctx.Limit = &limit
	return oruq
}

// Offset to start from.
func (oruq *OrgRoleUserQuery) Offset(offset int) *OrgRoleUserQuery {
	oruq.ctx.Offset = &offset
	return oruq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (oruq *OrgRoleUserQuery) Unique(unique bool) *OrgRoleUserQuery {
	oruq.ctx.Unique = &unique
	return oruq
}

// Order specifies how the records should be ordered.
func (oruq *OrgRoleUserQuery) Order(o ...orgroleuser.OrderOption) *OrgRoleUserQuery {
	oruq.order = append(oruq.order, o...)
	return oruq
}

// QueryOrgRole chains the current query on the "org_role" edge.
func (oruq *OrgRoleUserQuery) QueryOrgRole() *OrgRoleQuery {
	query := (&OrgRoleClient{config: oruq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := oruq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := oruq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(orgroleuser.Table, orgroleuser.FieldID, selector),
			sqlgraph.To(orgrole.Table, orgrole.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, orgroleuser.OrgRoleTable, orgroleuser.OrgRoleColumn),
		)
		schemaConfig := oruq.schemaConfig
		step.To.Schema = schemaConfig.OrgRole
		step.Edge.Schema = schemaConfig.OrgRoleUser
		fromU = sqlgraph.SetNeighbors(oruq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOrgUser chains the current query on the "org_user" edge.
func (oruq *OrgRoleUserQuery) QueryOrgUser() *OrgUserQuery {
	query := (&OrgUserClient{config: oruq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := oruq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := oruq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(orgroleuser.Table, orgroleuser.FieldID, selector),
			sqlgraph.To(orguser.Table, orguser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, orgroleuser.OrgUserTable, orgroleuser.OrgUserColumn),
		)
		schemaConfig := oruq.schemaConfig
		step.To.Schema = schemaConfig.OrgUser
		step.Edge.Schema = schemaConfig.OrgRoleUser
		fromU = sqlgraph.SetNeighbors(oruq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first OrgRoleUser entity from the query.
// Returns a *NotFoundError when no OrgRoleUser was found.
func (oruq *OrgRoleUserQuery) First(ctx context.Context) (*OrgRoleUser, error) {
	nodes, err := oruq.Limit(1).All(setContextOp(ctx, oruq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{orgroleuser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (oruq *OrgRoleUserQuery) FirstX(ctx context.Context) *OrgRoleUser {
	node, err := oruq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OrgRoleUser ID from the query.
// Returns a *NotFoundError when no OrgRoleUser ID was found.
func (oruq *OrgRoleUserQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oruq.Limit(1).IDs(setContextOp(ctx, oruq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{orgroleuser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (oruq *OrgRoleUserQuery) FirstIDX(ctx context.Context) int {
	id, err := oruq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OrgRoleUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OrgRoleUser entity is found.
// Returns a *NotFoundError when no OrgRoleUser entities are found.
func (oruq *OrgRoleUserQuery) Only(ctx context.Context) (*OrgRoleUser, error) {
	nodes, err := oruq.Limit(2).All(setContextOp(ctx, oruq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{orgroleuser.Label}
	default:
		return nil, &NotSingularError{orgroleuser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (oruq *OrgRoleUserQuery) OnlyX(ctx context.Context) *OrgRoleUser {
	node, err := oruq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OrgRoleUser ID in the query.
// Returns a *NotSingularError when more than one OrgRoleUser ID is found.
// Returns a *NotFoundError when no entities are found.
func (oruq *OrgRoleUserQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oruq.Limit(2).IDs(setContextOp(ctx, oruq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{orgroleuser.Label}
	default:
		err = &NotSingularError{orgroleuser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (oruq *OrgRoleUserQuery) OnlyIDX(ctx context.Context) int {
	id, err := oruq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OrgRoleUsers.
func (oruq *OrgRoleUserQuery) All(ctx context.Context) ([]*OrgRoleUser, error) {
	ctx = setContextOp(ctx, oruq.ctx, "All")
	if err := oruq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OrgRoleUser, *OrgRoleUserQuery]()
	return withInterceptors[[]*OrgRoleUser](ctx, oruq, qr, oruq.inters)
}

// AllX is like All, but panics if an error occurs.
func (oruq *OrgRoleUserQuery) AllX(ctx context.Context) []*OrgRoleUser {
	nodes, err := oruq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OrgRoleUser IDs.
func (oruq *OrgRoleUserQuery) IDs(ctx context.Context) (ids []int, err error) {
	if oruq.ctx.Unique == nil && oruq.path != nil {
		oruq.Unique(true)
	}
	ctx = setContextOp(ctx, oruq.ctx, "IDs")
	if err = oruq.Select(orgroleuser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (oruq *OrgRoleUserQuery) IDsX(ctx context.Context) []int {
	ids, err := oruq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (oruq *OrgRoleUserQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, oruq.ctx, "Count")
	if err := oruq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, oruq, querierCount[*OrgRoleUserQuery](), oruq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (oruq *OrgRoleUserQuery) CountX(ctx context.Context) int {
	count, err := oruq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (oruq *OrgRoleUserQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, oruq.ctx, "Exist")
	switch _, err := oruq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (oruq *OrgRoleUserQuery) ExistX(ctx context.Context) bool {
	exist, err := oruq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OrgRoleUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (oruq *OrgRoleUserQuery) Clone() *OrgRoleUserQuery {
	if oruq == nil {
		return nil
	}
	return &OrgRoleUserQuery{
		config:      oruq.config,
		ctx:         oruq.ctx.Clone(),
		order:       append([]orgroleuser.OrderOption{}, oruq.order...),
		inters:      append([]Interceptor{}, oruq.inters...),
		predicates:  append([]predicate.OrgRoleUser{}, oruq.predicates...),
		withOrgRole: oruq.withOrgRole.Clone(),
		withOrgUser: oruq.withOrgUser.Clone(),
		// clone intermediate query.
		sql:  oruq.sql.Clone(),
		path: oruq.path,
	}
}

// WithOrgRole tells the query-builder to eager-load the nodes that are connected to
// the "org_role" edge. The optional arguments are used to configure the query builder of the edge.
func (oruq *OrgRoleUserQuery) WithOrgRole(opts ...func(*OrgRoleQuery)) *OrgRoleUserQuery {
	query := (&OrgRoleClient{config: oruq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	oruq.withOrgRole = query
	return oruq
}

// WithOrgUser tells the query-builder to eager-load the nodes that are connected to
// the "org_user" edge. The optional arguments are used to configure the query builder of the edge.
func (oruq *OrgRoleUserQuery) WithOrgUser(opts ...func(*OrgUserQuery)) *OrgRoleUserQuery {
	query := (&OrgUserClient{config: oruq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	oruq.withOrgUser = query
	return oruq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		OrgRoleID int `json:"org_role_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OrgRoleUser.Query().
//		GroupBy(orgroleuser.FieldOrgRoleID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (oruq *OrgRoleUserQuery) GroupBy(field string, fields ...string) *OrgRoleUserGroupBy {
	oruq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OrgRoleUserGroupBy{build: oruq}
	grbuild.flds = &oruq.ctx.Fields
	grbuild.label = orgroleuser.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		OrgRoleID int `json:"org_role_id,omitempty"`
//	}
//
//	client.OrgRoleUser.Query().
//		Select(orgroleuser.FieldOrgRoleID).
//		Scan(ctx, &v)
func (oruq *OrgRoleUserQuery) Select(fields ...string) *OrgRoleUserSelect {
	oruq.ctx.Fields = append(oruq.ctx.Fields, fields...)
	sbuild := &OrgRoleUserSelect{OrgRoleUserQuery: oruq}
	sbuild.label = orgroleuser.Label
	sbuild.flds, sbuild.scan = &oruq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OrgRoleUserSelect configured with the given aggregations.
func (oruq *OrgRoleUserQuery) Aggregate(fns ...AggregateFunc) *OrgRoleUserSelect {
	return oruq.Select().Aggregate(fns...)
}

func (oruq *OrgRoleUserQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range oruq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, oruq); err != nil {
				return err
			}
		}
	}
	for _, f := range oruq.ctx.Fields {
		if !orgroleuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if oruq.path != nil {
		prev, err := oruq.path(ctx)
		if err != nil {
			return err
		}
		oruq.sql = prev
	}
	return nil
}

func (oruq *OrgRoleUserQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OrgRoleUser, error) {
	var (
		nodes       = []*OrgRoleUser{}
		_spec       = oruq.querySpec()
		loadedTypes = [2]bool{
			oruq.withOrgRole != nil,
			oruq.withOrgUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OrgRoleUser).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OrgRoleUser{config: oruq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = oruq.schemaConfig.OrgRoleUser
	ctx = internal.NewSchemaConfigContext(ctx, oruq.schemaConfig)
	if len(oruq.modifiers) > 0 {
		_spec.Modifiers = oruq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, oruq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := oruq.withOrgRole; query != nil {
		if err := oruq.loadOrgRole(ctx, query, nodes, nil,
			func(n *OrgRoleUser, e *OrgRole) { n.Edges.OrgRole = e }); err != nil {
			return nil, err
		}
	}
	if query := oruq.withOrgUser; query != nil {
		if err := oruq.loadOrgUser(ctx, query, nodes, nil,
			func(n *OrgRoleUser, e *OrgUser) { n.Edges.OrgUser = e }); err != nil {
			return nil, err
		}
	}
	for i := range oruq.loadTotal {
		if err := oruq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (oruq *OrgRoleUserQuery) loadOrgRole(ctx context.Context, query *OrgRoleQuery, nodes []*OrgRoleUser, init func(*OrgRoleUser), assign func(*OrgRoleUser, *OrgRole)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*OrgRoleUser)
	for i := range nodes {
		fk := nodes[i].OrgRoleID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(orgrole.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "org_role_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (oruq *OrgRoleUserQuery) loadOrgUser(ctx context.Context, query *OrgUserQuery, nodes []*OrgRoleUser, init func(*OrgRoleUser), assign func(*OrgRoleUser, *OrgUser)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*OrgRoleUser)
	for i := range nodes {
		fk := nodes[i].OrgUserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(orguser.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "org_user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (oruq *OrgRoleUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := oruq.querySpec()
	_spec.Node.Schema = oruq.schemaConfig.OrgRoleUser
	ctx = internal.NewSchemaConfigContext(ctx, oruq.schemaConfig)
	if len(oruq.modifiers) > 0 {
		_spec.Modifiers = oruq.modifiers
	}
	_spec.Node.Columns = oruq.ctx.Fields
	if len(oruq.ctx.Fields) > 0 {
		_spec.Unique = oruq.ctx.Unique != nil && *oruq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, oruq.driver, _spec)
}

func (oruq *OrgRoleUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(orgroleuser.Table, orgroleuser.Columns, sqlgraph.NewFieldSpec(orgroleuser.FieldID, field.TypeInt))
	_spec.From = oruq.sql
	if unique := oruq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if oruq.path != nil {
		_spec.Unique = true
	}
	if fields := oruq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orgroleuser.FieldID)
		for i := range fields {
			if fields[i] != orgroleuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if oruq.withOrgRole != nil {
			_spec.Node.AddColumnOnce(orgroleuser.FieldOrgRoleID)
		}
		if oruq.withOrgUser != nil {
			_spec.Node.AddColumnOnce(orgroleuser.FieldOrgUserID)
		}
	}
	if ps := oruq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := oruq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := oruq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := oruq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (oruq *OrgRoleUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(oruq.driver.Dialect())
	t1 := builder.Table(orgroleuser.Table)
	columns := oruq.ctx.Fields
	if len(columns) == 0 {
		columns = orgroleuser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if oruq.sql != nil {
		selector = oruq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if oruq.ctx.Unique != nil && *oruq.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(oruq.schemaConfig.OrgRoleUser)
	ctx = internal.NewSchemaConfigContext(ctx, oruq.schemaConfig)
	selector.WithContext(ctx)
	for _, p := range oruq.predicates {
		p(selector)
	}
	for _, p := range oruq.order {
		p(selector)
	}
	if offset := oruq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := oruq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OrgRoleUserGroupBy is the group-by builder for OrgRoleUser entities.
type OrgRoleUserGroupBy struct {
	selector
	build *OrgRoleUserQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (orugb *OrgRoleUserGroupBy) Aggregate(fns ...AggregateFunc) *OrgRoleUserGroupBy {
	orugb.fns = append(orugb.fns, fns...)
	return orugb
}

// Scan applies the selector query and scans the result into the given value.
func (orugb *OrgRoleUserGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, orugb.build.ctx, "GroupBy")
	if err := orugb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrgRoleUserQuery, *OrgRoleUserGroupBy](ctx, orugb.build, orugb, orugb.build.inters, v)
}

func (orugb *OrgRoleUserGroupBy) sqlScan(ctx context.Context, root *OrgRoleUserQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(orugb.fns))
	for _, fn := range orugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*orugb.flds)+len(orugb.fns))
		for _, f := range *orugb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*orugb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := orugb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OrgRoleUserSelect is the builder for selecting fields of OrgRoleUser entities.
type OrgRoleUserSelect struct {
	*OrgRoleUserQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (orus *OrgRoleUserSelect) Aggregate(fns ...AggregateFunc) *OrgRoleUserSelect {
	orus.fns = append(orus.fns, fns...)
	return orus
}

// Scan applies the selector query and scans the result into the given value.
func (orus *OrgRoleUserSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, orus.ctx, "Select")
	if err := orus.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrgRoleUserQuery, *OrgRoleUserSelect](ctx, orus.OrgRoleUserQuery, orus, orus.inters, v)
}

func (orus *OrgRoleUserSelect) sqlScan(ctx context.Context, root *OrgRoleUserQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(orus.fns))
	for _, fn := range orus.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*orus.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := orus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
